<!DOCTYPE html>
<html lang="zh">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>

  </style>

</head>

<body>

  <script src="myPromise.js"></script>
  <script>
    const p1 = new MyPromise((resolve, reject) => {
      // resolve(100);
      /**
       * 同步resolve和异步resolve是不会同时执行的，如果上面resolve(100)执行了，
       * 下面的setTimeout就不会执行
      */
      setTimeout(() => {
        console.log('setTimeout 100')
        reject(100);
      }, 500)
    })


    // 为什么实例化之后就可以调用.then,.catch因为实例本来就是可以调用then里面的方法的
    p1.catch(err => {
      console.log('捕获:', err); // 捕获: error
      return '修复后的值';
    }).then(res => {
      console.log('后续处理:', res); // 后续处理: 修复后的值
    });
    // // 打印下这个是什么
    // console.log('p13==>', p13)

    // // ?? p2,p3是什么
    const p2 = MyPromise.resolve(200);
    const p3 = MyPromise.reject('一个错误信息');
    const p4 = MyPromise.all([p1, p2]);
    console.log('p4==>', p4)
    const p5 = MyPromise.race([p1, p2]);
    console.log('p5==>', p5)

  </script>
</body>

</html>